spring:
  application:
    name: RideOn
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  flyway:
    enabled: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: test
            client-secret: test
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
              - phone_number
              - birthday
              - birthyear
          google:
            client-id: test
            client-secret: test
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope:
              - profile
              - email
          naver:
            client-id: test
            client-secret: test
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope:
              - name
              - email
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  logging:
    level:
      org.springframework.boot.autoconfigure.security: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true
jwt:
  secret: test-secret-key-for-testing-purposes-only
  expiration: 36000000
  token:
    access-expiration: 900000
    refresh-expiration: 604800000
naver:
  client-id: test
  client-secret: test
site:
  url:
    frontend: "http://localhost:3000" 